name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      GITHUB_URL:
        description: 'GIT_URL to clone kernel source'
        required: true
        default: '-b A528BXXSBGYI3 https://github.com/SN-Abdullah-Al-Noman/SM-A528B'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: 1️⃣ Checkout code
        uses: actions/checkout@v2

      - name: 2️⃣ Installing packages.
        run: |
          sudo apt update -y && sudo apt install -y \
              apt-utils nano bison ca-certificates curl flex gcc git libc6-dev libssl-dev \
              openssl ssh wget zip zstd sudo make clang gcc-arm-linux-gnueabi \
              software-properties-common build-essential libarchive-tools \
              gcc-aarch64-linux-gnu libffi-dev libncurses5-dev zlib1g zlib1g-dev \
              libreadline-dev libbz2-dev libsqlite3-dev pigz python3 cpio lld \
              p7zip-full xz-utils tar libelf-dev libudev-dev libpci-dev \
              libiberty-dev pkg-config llvm clang-tools fakeroot ccache \
              libcap-dev libunwind-dev gawk bc u-boot-tools device-tree-compiler \
              liblzma-dev libncursesw5-dev python3-pip git-core gnupg \
              libc6-dev-i386 x11proto-core-dev libx11-dev lib32z1-dev \
              libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig libtinfo5

      - name: 3️⃣ Cloning kernel source.
        run: |
          sudo git clone ${{ github.event.inputs.GITHUB_URL }} kernel_source

      - name: 4️⃣ Cloning toolchain.
        run: |
          sudo git clone https://github.com/SN-Abdullah-Al-Noman/clang-r383902
          sudo git clone https://github.com/SN-Abdullah-Al-Noman/aarch64-linux-android-4.9
          sudo git clone -b 10.0 https://github.com/SN-Abdullah-Al-Noman/llvm-arm-toolchain-ship llvm-arm-toolchain-ship/10.0
          
      - name: 5️⃣ Starting kernel compile.
        run: |
          cd kernel_source && sudo touch logs.txt && sudo chmod a+w logs.txt && sudo bash build_kernel.sh |& tee logs.txt
          sudo curl -F chat_id=2081111916 -F document=@logs.txt -F caption="logs.txt" https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendDocument

      - name: 6️⃣ Uploading kernel in telegram.
        run: |
          cd kernel_source/arch/arm64/boot
          sudo curl \
              -F "chat_id=2081111916" \
              -F "document=@Image" \
              -F "caption=${{ github.event.inputs.GITHUB_URL }}" \
              "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendDocument"
